#!/usr/bin/env bash

export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PATH:~/.local/bin"
export PATH="$PATH:/mnt/c/Users/tle/AppData/Local/Programs/Microsoft VS Code/bin"
export PATH="~/.kubectx:$PATH"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

export PYENV_ROOT="$HOME/.pyenv"

export GOENV_ROOT="$HOME/.goenv"
export PATH="$GOENV_ROOT/bin:$PATH"
